create the html of the onboarding page and add img
GSG-CF05/finance-app-team2 pull request #9
Opened 2022-02-07 09:38 UTC by ahlam377

relates #8

2022-02-07 09:42 UTC, moustf requested changes

2022-02-07 09:42 UTC, moustf commented on index.html
> +    <h1 class="heade">Finance</h1>
Financy

2022-02-07 09:42 UTC, moustf commented on index.html
> +    <img src="img.jpg" alt="">
fill the alt attr with text to do it in the best practices.

2022-02-07 09:42 UTC, moustf commented on index.html
> +      <p1>Have all your finances </p1><br/>
the p element is a Block-level element, so it will add a line break by default.
no need for <br/>

2022-02-07 10:10 UTC, muhannaAtalla20 commented on index.html
> +      <p1>Have all your finances </p1><br/>
<p></p> not <p1></p1>

2022-02-07 10:11 UTC, muhannaAtalla20 commented on index.html
> +      <p2>in one place!</p2>
paragraph tag not content number 2

2022-02-07 10:30 UTC, muhannaAtalla20 approved these changes

2022-02-07 10:31 UTC, moustf submitted a review, later dismissed
Couldn't be better👏

2022-02-07 16:28 UTC, MohammedAbuSamra requested changes
Request changes

2022-02-07 19:39 UTC, moustf requested changes

2022-02-07 19:39 UTC, moustf commented on assets/css/style.css
> +
There are lots of empty lines, format the files by Prettier, click alt+shift+f

2022-02-07 19:39 UTC, moustf commented on index.html
> +    <div>
You need to put class-"container" for the div.

2022-02-07 19:39 UTC, moustf commented on index.html
> +      <h1><strong>Financy</strong></h1>
It's always better to control the styles through CSS code, you can put a font-weight: bolder; to the h1 tag.
No need for <strong> element.

2022-02-07 19:39 UTC, moustf commented on index.html
> +  </body>
Also, try to format it with Prettier extension.

2022-02-08 06:37 UTC, moustf requested changes

2022-02-08 06:37 UTC, moustf commented on index.html
> +
Put these two tags here
<!DOCTYPE html>
<html>

2022-02-08 06:37 UTC, moustf commented on index.html
> +    <img src="img.jpg" alt="Onboarding design picture">
The image should be in the assets/images, not in the root.

2022-02-08 06:37 UTC, moustf commented on index.html
> +      <p> Have all your finances<br> in one place!</p></div>
The <br> tag isn't a good practice, you can use two <p> elements.

2022-02-08 06:37 UTC, moustf commented on assets/css/style.css
> +    position:absolute;
I think it will be better if you center the container vertically on the page.

2022-02-08 06:37 UTC, moustf commented on index.html
> +      <button type="button" class="continue">continue</button>
The continue button should take to the home page, wrap the button inside a <a> tag to do that

2022-02-08 15:54 UTC, MohammedAbuSamra approved these changes
Awesome, thank you.

2022-02-08 16:09 UTC, muhannaAtalla20 approved these changes

2022-02-08 17:20 UTC, moustf approved these changes

2022-02-08 17:23 UTC, merged